pipeline {
    agent any
    parameters{
        string(name: 'LOGIN', defaultValue: '', description: 'Es un identificador único que se compone del nombre y el apellido. Sin espacios.')
        string(name: 'NOMBRE_COMPLETO', defaultValue: '', description: 'Nombre completo del usuario (Nombre y Apellido).')
        choice(name: 'DEPARTAMENTO', choices: ['contabilidad', 'finanzas', 'tecnología'], description: 'Este es el grupo que corresponde al área del usuario.')
    }
    stages {
        stage('Validar Datos') {
            steps {
                script {
                    if (!params.LOGIN || !params.NOMBRE_COMPLETO || !params.DEPARTAMENTO) {
                        error("Todos los parámetros son obligatorios.")
                    }
                }
            }
        }
        stage('Crear Usuario') {
            steps {
                script {
                    // Mejoro el manejo de variable como de ambiente
                    env.PASS_TEMPORAL = sh(
                        script: 'openssl rand -base64 8',
                        returnStdout: true
                    ).trim()
                }
                sh '''
                #!/bin/bash

                # Variables del script
                LOGIN="${LOGIN}"
                NOMBRE_COMPLETO="${NOMBRE_COMPLETO}"
                DEPARTAMENTO="${DEPARTAMENTO}"
                PASS_TEMPORAL="${PASS_TEMPORAL}"
                HOME_DIR="/home/${LOGIN}"

                # Creo el grupo si no existe
                if ! getent group "${DEPARTAMENTO}" >/dev/null; then
                    sudo groupadd "${DEPARTAMENTO}"
                fi

                # Creo el usuario
                sudo useradd "${LOGIN}" -m -s /bin/bash -d "${HOME_DIR}" -c "${NOMBRE_COMPLETO}" -p ${PASS_TEMPORAL}

                # Añadir el usuario al grupo
                sudo usermod -aG "${DEPARTAMENTO}" "${LOGIN}"

                # Forzar cambio de contraseña en el próximo inicio de sesión
                sudo chage -d 0 "${LOGIN}"

                # Configurar permisos del directorio home
                sudo chown -R "${LOGIN}:${DEPARTAMENTO}" "${HOME_DIR}"

                # Salidas de validación
                echo "PASSWORD TEMPORAL: ${PASS_TEMPORAL}" > outputs.txt

                PERMISOS_HOME=$(sudo ls -lha "${HOME_DIR}" | grep "${LOGIN}$")
                echo "PERMISOS del HOME: ${PERMISOS_HOME}" >> outputs.txt
                
                echo "DATOS DEL USUARIO: $(id ${LOGIN})" >> outputs.txt
                '''
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'outputs.txt', onlyIfSuccessful: true
        }
        success {
            echo "Usuario creado con éxito. La contraseña temporal está disponible en los artefactos."
        }
        failure {
            echo "Error durante la creación del usuario."
        }
    }
}